if (typeof renderMathInElement === 'function') renderMathInElement(document.body, { delimiters: [{ left: '\\[', right: '\\]', display: true }, { left: '\\(', right: '\\)', display: false }], throwOnError: false });

const { StateVector, Complex, gates, QuantumCircuit, CircuitEvaluator } = QuantumCore;
const stateButtons = document.querySelectorAll('.state-button');
const gateButtons = document.querySelectorAll('.gate-button');
const diracDisplay = document.querySelector('#diracDisplay');
const probabilityZero = document.querySelector('#probabilityZero');
const probabilityOne = document.querySelector('#probabilityOne');
const probabilityZeroBar = document.querySelector('#probabilityZeroBar');
const probabilityOneBar = document.querySelector('#probabilityOneBar');
const gateHistory = document.querySelector('#gateHistory');
const blochCanvas = document.querySelector('#blochCanvas');
const blochContext = blochCanvas.getContext('2d');
const blochCoordinates = document.querySelector('#blochCoordinates');
let currentQuantumState = new StateVector(1, 0);

function cleanNumber(value) { return Math.abs(value) < 1e-10 ? 0 : Number(value.toFixed(4)); }
function formatCoefficient(value) { const real = cleanNumber(value.real); const imaginary = cleanNumber(value.imaginary); if (imaginary === 0 && Math.abs(Math.abs(real) - .7071) < .001) return real < 0 ? '-\\frac{1}{\\sqrt{2}}' : '\\frac{1}{\\sqrt{2}}'; if (imaginary === 0) return String(real); if (real === 0) return `${imaginary}i`; return `(${real}${imaginary < 0 ? '' : '+'}${imaginary}i)`; }
function getBlochCoordinates() { const coherence = currentQuantumState.alpha.conjugate().multiply(currentQuantumState.beta); const probabilities = currentQuantumState.probabilities(); return { x: 2 * coherence.real, y: 2 * coherence.imaginary, z: probabilities.zero - probabilities.one }; }
function drawArrow(context, fromX, fromY, toX, toY) { const angle = Math.atan2(toY - fromY, toX - fromX); const head = 10; context.beginPath(); context.moveTo(toX, toY); context.lineTo(toX - head * Math.cos(angle - Math.PI / 6), toY - head * Math.sin(angle - Math.PI / 6)); context.moveTo(toX, toY); context.lineTo(toX - head * Math.cos(angle + Math.PI / 6), toY - head * Math.sin(angle + Math.PI / 6)); context.stroke(); }
function drawBlochSphere() { const width = blochCanvas.clientWidth; const height = blochCanvas.clientHeight; if (!width || !height) return; const ratio = window.devicePixelRatio || 1; blochCanvas.width = Math.floor(width * ratio); blochCanvas.height = Math.floor(height * ratio); blochContext.setTransform(ratio, 0, 0, ratio, 0, 0); blochContext.clearRect(0, 0, width, height); blochContext.fillStyle = '#07121c'; blochContext.fillRect(0, 0, width, height); const radius = Math.min(width * .27, height * .37); const centerX = width / 2; const centerY = height / 2 + 8; const coordinates = getBlochCoordinates(); const projectedX = centerX + radius * (.82 * coordinates.x + .27 * coordinates.y); const projectedY = centerY - radius * (.82 * coordinates.z + .27 * coordinates.y); blochCoordinates.textContent = `x ${coordinates.x.toFixed(2)} · y ${coordinates.y.toFixed(2)} · z ${coordinates.z.toFixed(2)}`; blochContext.strokeStyle = 'rgba(139,160,181,.45)'; blochContext.beginPath(); blochContext.arc(centerX, centerY, radius, 0, Math.PI * 2); blochContext.stroke(); blochContext.setLineDash([4,5]); blochContext.beginPath(); blochContext.ellipse(centerX, centerY, radius, radius * .27, 0, 0, Math.PI * 2); blochContext.stroke(); blochContext.setLineDash([]); blochContext.strokeStyle = 'rgba(92,225,230,.5)'; blochContext.beginPath(); blochContext.moveTo(centerX, centerY - radius - 15); blochContext.lineTo(centerX, centerY + radius + 15); blochContext.moveTo(centerX - radius - 15, centerY); blochContext.lineTo(centerX + radius + 15, centerY); blochContext.moveTo(centerX - radius * .72, centerY + radius * .27); blochContext.lineTo(centerX + radius * .72, centerY - radius * .27); blochContext.stroke(); blochContext.fillStyle = '#ecf5ff'; blochContext.font = '600 12px Exo 2, sans-serif'; blochContext.fillText('Z', centerX + 8, centerY - radius - 18); blochContext.fillText('X', centerX + radius + 18, centerY + 4); blochContext.fillText('Y', centerX + radius * .74, centerY - radius * .27 - 8); blochContext.fillStyle = '#c6f36b'; blochContext.fillText('|0⟩', centerX + 10, centerY - radius + 3); blochContext.fillStyle = '#ffad66'; blochContext.fillText('|1⟩', centerX + 10, centerY + radius + 3); blochContext.strokeStyle = '#c6f36b'; blochContext.lineWidth = 3; blochContext.beginPath(); blochContext.moveTo(centerX, centerY); blochContext.lineTo(projectedX, projectedY); blochContext.stroke(); drawArrow(blochContext, centerX, centerY, projectedX, projectedY); blochContext.fillStyle = '#c6f36b'; blochContext.beginPath(); blochContext.arc(projectedX, projectedY, 5, 0, Math.PI * 2); blochContext.fill(); }
function renderQuantumState() { const probabilities = currentQuantumState.probabilities(); const zeroPercent = Math.round(probabilities.zero * 100); const onePercent = Math.round(probabilities.one * 100); const alpha = formatCoefficient(currentQuantumState.alpha); const beta = formatCoefficient(currentQuantumState.beta); const betaSign = beta.startsWith('-') ? ' - ' : ' + '; const betaValue = beta.startsWith('-') ? beta.slice(1) : beta; const formula = `${alpha}${String.raw`\left|0\right\rangle`}${beta === '0' ? '' : `${betaSign}${betaValue}${String.raw`\left|1\right\rangle`}`}`; probabilityZero.textContent = `${zeroPercent}%`; probabilityOne.textContent = `${onePercent}%`; probabilityZeroBar.style.width = `${zeroPercent}%`; probabilityOneBar.style.width = `${onePercent}%`; if (typeof katex !== 'undefined') katex.render(formula, diracDisplay, { throwOnError: false }); drawBlochSphere(); }
function resetQuantumState(name) { const states = { zero: [1, 0], one: [0, 1], plus: [new Complex(1 / Math.sqrt(2), 0), new Complex(1 / Math.sqrt(2), 0)] }; currentQuantumState = new StateVector(...states[name]); stateButtons.forEach((button) => button.classList.toggle('active', button.dataset.state === name)); gateHistory.textContent = `RESET / |${name === 'plus' ? '+' : name === 'zero' ? '0' : '1'}⟩`; renderQuantumState(); }
stateButtons.forEach((button) => button.addEventListener('click', () => resetQuantumState(button.dataset.state)));
gateButtons.forEach((button) => button.addEventListener('click', () => { currentQuantumState = gates[button.dataset.gate].multiplyState(currentQuantumState); gateHistory.textContent = `APPLIED / ${button.dataset.gate}`; renderQuantumState(); }));
renderQuantumState();

const particleSlider = document.querySelector('#particleSlider'); const particleOutput = document.querySelector('#particleOutput'); const wavelengthSlider = document.querySelector('#wavelengthSlider'); const wavelengthOutput = document.querySelector('#wavelengthOutput'); const slitSlider = document.querySelector('#slitSlider'); const slitOutput = document.querySelector('#slitOutput'); const simulation = document.querySelector('#simulation'); const canvas = document.querySelector('#doubleSlitCanvas'); const canvasContext = canvas.getContext('2d'); let simulationFrame; let electronHits = []; let visibleHits = 0;
function getSimulationValues() { return { particles: Number(particleSlider.value), wavelength: Number(wavelengthSlider.value), slitWidth: Number(slitSlider.value) }; }
function probabilityAt(position, wavelength, slitWidth) { const normalized = position / slitWidth; const sinc = normalized === 0 ? 1 : Math.sin(normalized) / normalized; return Math.max(.005, sinc ** 2 * Math.cos(position * 2.8 / wavelength) ** 2); }
function createElectronHits(count, wavelength, slitWidth) { const hits = []; const spread = 125; let maximum = 0; for (let position = -spread; position <= spread; position += 2) maximum = Math.max(maximum, probabilityAt(position, wavelength, slitWidth)); while (hits.length < count) { const position = (Math.random() * 2 - 1) * spread; if (Math.random() * maximum < probabilityAt(position, wavelength, slitWidth)) hits.push(position); } return hits; }
function drawDoubleSlit() { const width = canvas.clientWidth; const height = canvas.clientHeight; if (!width || !height) return; const values = getSimulationValues(); canvasContext.clearRect(0, 0, width, height); canvasContext.fillStyle = '#07121c'; canvasContext.fillRect(0, 0, width, height); const barrierX = width * .31; const screenX = width * .83; const curveTop = height * .68; const screenTop = 20; const screenHeight = curveTop - 42; const centerY = screenTop + screenHeight / 2; const scale = Math.min(1, width / 520); canvasContext.strokeStyle = 'rgba(92,225,230,.35)'; canvasContext.setLineDash([4,5]); canvasContext.beginPath(); canvasContext.moveTo(barrierX, screenTop); canvasContext.lineTo(barrierX, curveTop - 20); canvasContext.stroke(); canvasContext.setLineDash([]); canvasContext.fillStyle = '#ecf5ff'; canvasContext.fillRect(barrierX - 2, screenTop, 4, screenHeight * .37); canvasContext.fillRect(barrierX - 2, centerY + 17, 4, screenHeight * .37); canvasContext.fillStyle = '#5ce1e6'; canvasContext.fillRect(barrierX - 2, centerY - 17, 4, 34); canvasContext.strokeStyle = 'rgba(92,225,230,.7)'; canvasContext.strokeRect(screenX, screenTop, 3, screenHeight); electronHits.slice(0, visibleHits).forEach((position) => { canvasContext.fillStyle = 'rgba(198,243,107,.82)'; canvasContext.beginPath(); canvasContext.arc(screenX, centerY + position * scale, 1.7, 0, Math.PI * 2); canvasContext.fill(); }); canvasContext.strokeStyle = '#ffad66'; canvasContext.lineWidth = 2; canvasContext.beginPath(); for (let x = 0; x <= width; x += 3) { const position = ((x / width) * 2 - 1) * 125; const y = curveTop - probabilityAt(position, values.wavelength, values.slitWidth) * 48; if (x === 0) canvasContext.moveTo(x, y); else canvasContext.lineTo(x, y); } canvasContext.stroke(); canvasContext.lineWidth = 1; canvasContext.fillStyle = '#8ba0b5'; canvasContext.font = '10px Exo 2, sans-serif'; canvasContext.fillText('|ψ|²  PROBABILITY DISTRIBUTION', 12, curveTop + 18); canvasContext.fillText('ELECTRON SCREEN', Math.max(12, screenX - 70), screenTop - 6); }
function resizeCanvas() { const ratio = window.devicePixelRatio || 1; const bounds = canvas.getBoundingClientRect(); canvas.width = Math.max(1, Math.floor(bounds.width * ratio)); canvas.height = Math.max(1, Math.floor(bounds.height * ratio)); canvasContext.setTransform(ratio, 0, 0, ratio, 0, 0); drawDoubleSlit(); }
function updateSimulation() { const values = getSimulationValues(); particleOutput.textContent = values.particles; wavelengthOutput.textContent = values.wavelength; slitOutput.textContent = values.slitWidth; electronHits = createElectronHits(values.particles, values.wavelength, values.slitWidth); visibleHits = 0; cancelAnimationFrame(simulationFrame); let frame = 0; const animate = () => { visibleHits = Math.min(values.particles, Math.ceil((frame + 1) * values.particles / 18)); drawDoubleSlit(); frame += 1; if (frame < 18) simulationFrame = requestAnimationFrame(animate); }; animate(); }
[particleSlider, wavelengthSlider, slitSlider].forEach((slider) => slider.addEventListener('input', updateSimulation)); document.querySelector('#simulateButton').addEventListener('click', updateSimulation); window.addEventListener('resize', resizeCanvas); updateSimulation(); resizeCanvas();

const composerQubits = 4; const composerSteps = 8; const circuitCells = document.querySelector('#circuitCells'); const timeLabels = document.querySelector('#timeLabels'); const composerStatus = document.querySelector('#composerStatus'); const probabilityChart = document.querySelector('#probabilityChart'); const amplitudeChart = document.querySelector('#amplitudeChart'); let selectedComposerGate = null; let pendingCNOT = null; let composerGrid = Array.from({ length: composerQubits }, () => Array(composerSteps).fill(null));
for (let step = 0; step < composerSteps; step += 1) { const label = document.createElement('span'); label.textContent = `T${step + 1}`; timeLabels.appendChild(label); }
for (let qubit = 0; qubit < composerQubits; qubit += 1) for (let step = 0; step < composerSteps; step += 1) { const cell = document.createElement('button'); cell.type = 'button'; cell.className = 'circuit-cell'; cell.dataset.qubit = qubit; cell.dataset.step = step; cell.setAttribute('role', 'gridcell'); cell.setAttribute('aria-label', `q[${qubit}], 時間步 ${step + 1}`); circuitCells.appendChild(cell); }
function cellAt(qubit, step) { return circuitCells.querySelector(`[data-qubit="${qubit}"][data-step="${step}"]`); }
function chooseComposerGate(gate) { selectedComposerGate = gate; pendingCNOT = null; document.querySelectorAll('.library-gate').forEach((button) => button.classList.toggle('selected', button.dataset.composerGate === gate)); composerStatus.textContent = gate === 'CNOT' ? 'CNOT：點擊控制線，再點擊同一欄的目標線' : gate === 'M' ? '測量：點擊任一時間欄放置測量' : `${gate} 閘已選取，點擊任一量子線路格放置`; }
function renderCircuitGrid() { for (let qubit = 0; qubit < composerQubits; qubit += 1) for (let step = 0; step < composerSteps; step += 1) { const element = cellAt(qubit, step); const operation = composerGrid[qubit][step]; element.className = 'circuit-cell'; element.textContent = ''; if (!operation) continue; element.classList.add(`cell-${operation.type.toLowerCase()}`); if (operation.type === 'CNOT') { element.classList.add(operation.role === 'TARGET' ? 'cnot-target' : 'cnot-control'); element.textContent = operation.role === 'TARGET' ? '⊕' : '●'; } else element.textContent = operation.type === 'MEASURE' ? 'M' : operation.gate; } }
function removeCircuitOperation(qubit, step) { const operation = composerGrid[qubit][step]; if (!operation) return; if (operation.type === 'CNOT') { composerGrid[operation.control][operation.timeStep] = null; composerGrid[operation.target][operation.timeStep] = null; } else if (operation.type === 'MEASURE') for (let row = 0; row < composerQubits; row += 1) composerGrid[row][step] = null; else composerGrid[qubit][step] = null; renderCircuitGrid(); evaluateComposerCircuit(); }
function placeComposerGate(qubit, step) { if (!selectedComposerGate) { composerStatus.textContent = '請先從左側閘庫選擇一個邏輯閘'; return; } if (selectedComposerGate === 'CNOT') { if (!pendingCNOT) { if (composerGrid[qubit][step]) return; pendingCNOT = { control: qubit, timeStep: step }; composerStatus.textContent = `控制線 q[${qubit}] 已選取，請點擊 T${step + 1} 的另一條空白量子線`; cellAt(qubit, step).classList.add('pending-control'); return; } if (pendingCNOT.timeStep !== step || pendingCNOT.control === qubit || composerGrid[qubit][step]) { composerStatus.textContent = 'CNOT 目標必須是同一時間欄的另一條空白量子線'; return; } const operation = { type: 'CNOT', control: pendingCNOT.control, target: qubit, timeStep: step }; composerGrid[operation.control][step] = operation; composerGrid[operation.target][step] = { ...operation, role: 'TARGET' }; pendingCNOT = null; } else if (selectedComposerGate === 'M') { if (composerGrid.some((row) => row[step])) return; for (let row = 0; row < composerQubits; row += 1) composerGrid[row][step] = { type: 'MEASURE', timeStep: step }; } else { if (composerGrid[qubit][step]) return; composerGrid[qubit][step] = { type: 'SINGLE', gate: selectedComposerGate, qubit }; } renderCircuitGrid(); evaluateComposerCircuit(); }
function buildComposerCircuit() { const circuit = new QuantumCircuit(composerQubits, composerSteps); for (let qubit = 0; qubit < composerQubits; qubit += 1) for (let step = 0; step < composerSteps; step += 1) { const operation = composerGrid[qubit][step]; if (!operation) continue; if (operation.type === 'SINGLE') circuit.setGate(qubit, step, operation.gate); else if (operation.type === 'CNOT' && operation.role !== 'TARGET') circuit.addCNOT(operation.control, operation.target, step); else if (operation.type === 'MEASURE' && qubit === 0) circuit.addMeasurement(step); } return circuit; }
function createChartBars(container, type) { container.textContent = ''; for (let index = 0; index < 16; index += 1) { const item = document.createElement('div'); item.className = 'chart-bar-item'; item.innerHTML = `<div class="chart-bar-value">0%</div><div class="chart-bar-track"><span class="${type}-bar"></span></div><small>${index.toString(2).padStart(4, '0')}</small>`; container.appendChild(item); } }
function evaluateComposerCircuit() { const result = new CircuitEvaluator(buildComposerCircuit()).run(); const probabilities = result.state.probabilities(); const probabilityBars = probabilityChart.querySelectorAll('.probability-bar'); const amplitudeBars = amplitudeChart.querySelectorAll('.amplitude-bar'); result.state.amplitudes.forEach((amplitude, index) => { const probability = probabilities[index]; const magnitude = Math.sqrt(probability); probabilityBars[index].style.height = `${Math.max(2, probability * 100)}%`; probabilityBars[index].parentElement.previousElementSibling.textContent = `${Math.round(probability * 100)}%`; amplitudeBars[index].style.height = `${Math.max(2, magnitude * 100)}%`; amplitudeBars[index].parentElement.previousElementSibling.textContent = magnitude.toFixed(2); amplitudeBars[index].classList.toggle('complex-phase', Math.abs(amplitude.imaginary) > 1e-10); }); }
createChartBars(probabilityChart, 'probability'); createChartBars(amplitudeChart, 'amplitude'); document.querySelectorAll('.library-gate').forEach((button) => { button.addEventListener('click', () => chooseComposerGate(button.dataset.composerGate)); button.addEventListener('dragstart', (event) => { event.dataTransfer.setData('text/plain', button.dataset.composerGate); chooseComposerGate(button.dataset.composerGate); }); }); circuitCells.addEventListener('click', (event) => placeComposerGate(Number(event.target.dataset.qubit), Number(event.target.dataset.step))); circuitCells.addEventListener('contextmenu', (event) => { event.preventDefault(); removeCircuitOperation(Number(event.target.dataset.qubit), Number(event.target.dataset.step)); }); circuitCells.addEventListener('dragover', (event) => event.preventDefault()); circuitCells.addEventListener('drop', (event) => { event.preventDefault(); chooseComposerGate(event.dataTransfer.getData('text/plain')); placeComposerGate(Number(event.target.dataset.qubit), Number(event.target.dataset.step)); }); document.querySelector('#clearCircuitButton').addEventListener('click', () => { composerGrid = Array.from({ length: composerQubits }, () => Array(composerSteps).fill(null)); pendingCNOT = null; renderCircuitGrid(); evaluateComposerCircuit(); }); renderCircuitGrid(); evaluateComposerCircuit();
